### ISSUE TITLE
Error:(45, 13) Failed to resolve: me.wangyuwei:LoadingiVew:1.0.5

### ISSUE THREAD

**Issue by axelblaze15** [sqli-nantes/ethereum-android#1]
After adding compile 'me.wangyuwei:LoadingiVew:1.0.5' in dependencies in build.gradle of ethereum-android-sample., I got this error: Error:(45, 13) Failed to resolve: me.wangyuwei:LoadingiVew:1.0.5 . Any help would be appreciated !!

**Comment by Nigui** [comment]
Hi, have you tried using command line build with `./gradlew assemble --refresh-dependencies ` ?
Otherwise, can you post your `build.gradle` please ?
It doesn't seem to be related to ethereum-android library.

**Comment by axelblaze15** [comment]
build.gradle-
apply plugin: 'com.android.application'

buildscript {      
 repositories {    
    jcenter()    
}    

dependencies {
    classpath 'com.android.tools.build:gradle:2.3.1'
}
}   

android {    

compileSdkVersion 24
buildToolsVersion '25.0.0'

defaultConfig {
    applicationId "com.sqli.blockchain.ethereum_android_sample"
    minSdkVersion 21
    targetSdkVersion 24
    testInstrumentationRunner 
    "android.support.test.runner.AndroidJUnitRunner"

}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 
        'proguard-rules.pro'
    }
}
lintOptions {
    abortOnError false
}
}

task wrapper(type: Wrapper) {
gradleVersion = '3.1'
}

dependencies {
androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', 
{
    exclude group: 'com.android.support', module: 'support-annotations'
})
compile 'com.android.support:appcompat-v7:24.2.1'
testCompile 'junit:junit:4.12'
compile 'com.google.code.gson:gson:2.7'
compile 'me.relex:circleindicator:1.2.2@aar'
compile 'me.wangyuwei:LoadingiVew:1.0.5'
compile 'com.github.dmytrodanylyk.android-process-button:library:1.0.4'
compile 'com.sqli:ethereum-android:0.1.20170320@aar'
compile 'com.sqli:android-geth:0.1.20170320@aar'
compile 'com.sqli:ethereum-java-core:0.1.20170320'
compile 'ethereumandroid:geth:1.5.0-unstable'
}

repositories {
maven {
    url "http://dl.bintray.com/sqli-nantes/ethereum-android"
}
maven {
    url "http://dl.bintray.com/androidgeth/Geth"
}

    maven { url 'http://repo1.maven.org/maven2' }

}
